%% Model and simulation setup
system_model = @inverted_pendulum;
u_limit = [u_min, u_max];
t = 0 : dt : 4;
t1 = 0; 
t2 = 4;
M = 2;
reference_cutoff_angle = 5/180*pi; %angle when reference gets set to 0

disturbance = zeros(length(t), length(x0));
disturbance(t==2.5, 3) = 15/180*pi;
disturbance(t==3, 3) = -15/180*pi;

noise = [0.001/5, 0.005, 0.001/5, 0.005, 0.001];


%% MPC_L1 + gain_scheduling
controller = @gain_scheduling_lqr;
trajectory_file = 'MPC_trajectory_norm1.mat';

[states, control, states_measured, state_reference, control_reference] = ... 
test_controller(controller, ...
    system_model, trajectory_file, u_limit, ...
    t, M, reference_cutoff_angle, disturbance, noise);

plot_simulation_result(states, ...
    states_measured, control, state_reference, control_reference, ...
    t, t1, t2, u_limit)

%% MPC_L2 + gain_scheduling
controller = @gain_scheduling_lqr;
trajectory_file = 'MPC_trajectory_norm2.mat';

[states, control, states_measured, state_reference, control_reference] = ... 
test_controller(controller, ...
    system_model, trajectory_file, u_limit, ...
    t, M, reference_cutoff_angle, disturbance, noise);

plot_simulation_result(states, ...
    states_measured, control, state_reference, control_reference, ...
    t, t1, t2, u_limit)
%% Energy control + global_lqr
controller = @global_LQR;
trajectory_file = 'EnergyControl_trajectory.mat';

[states, control, states_measured, state_reference, control_reference] = ... 
test_controller(controller, ...
    system_model, trajectory_file, u_limit, ...
    t, M, reference_cutoff_angle, disturbance, noise);

plot_simulation_result(states, ...
    states_measured, control, state_reference, control_reference, ...
    t, t1, t2, u_limit)

%% EnergyShaping_trajectory + global_lqr
controller = @global_LQR;
trajectory_file = 'EnergyShaping_trajectory.mat';

[states, control, states_measured, state_reference, control_reference] = ... 
test_controller(controller, ...
    system_model, trajectory_file, u_limit, ...
    t, M, reference_cutoff_angle, disturbance, noise);

plot_simulation_result(states, ...
    states_measured, control, state_reference, control_reference, ...
    t, t1, t2, u_limit)

%% ExpControl_trajectory + global_lqr
controller = @global_LQR;
trajectory_file = 'ExpControl_trajectory.mat';

[states, control, states_measured, state_reference, control_reference] = ... 
test_controller(controller, ...
    system_model, trajectory_file, u_limit, ...
    t, M, reference_cutoff_angle, disturbance, noise);

plot_simulation_result(states, ...
    states_measured, control, state_reference, control_reference, ...
    t, t1, t2, u_limit)

